### ISSUE TITLE
Use custom variable for jumping to timeline

### ISSUE THREAD

**Issue by nroest** [bitfocus/companion-module-avstumpfl-pixera#4]
I'm trying to use custom variables to set the jump to timeline command so they can changed based on variables within companion. When I try to use those variables within the fields, it stays red and won't function when used. I tried using the API commands as listed in the reference manual on the website, but my knowledge stops there. Is there anyway to achieve this using the current module? Even just the api string I could use and add the custom variable into, that would be a massive help!

**Comment by gerbenvandekraats** [comment]
At the moment this will not work with the 'Goto Timecode' action because the fields have to be a number due to a [regex](https://github.com/bitfocus/companion-module-avstumpfl-pixera/blob/e745b28a9997e5e0fc3fdcee848758be3f8f1acd/avstumpfl-pixera.js#L563) on those fields. Same story for the 'Blend To Timecode' action.

But even if the above was not the problem, the module seems not to process variables at all. So i'm sorry but at the moment this module will not serve your needs.

I did a quick test with the 'Generic HTTP Requests' module and that seems to do what you want:

1. Add 'Generic HTTP Requests' module
2. Make sure you have setup the right [settings](https://help.pixera.one/api/api-test-website)
3. Add a 'HTTP Request: POST' action to your button
4. Enter your Pixera API adres: http://YOUR-DOMAIN-OR-IP:1400/api_test/index.html
5. Choose 'application/json' as Content-type
6. Header input(JSON) can be empty
7. Paste this to your 'Body' field (and of course rename the name of your timeline and variable tag to the name of your timeline and variable):
`{"jsonrpc":"2.0", "id":44, "method":"Pixera.Compound.setCurrentTimeOfTimelineInSeconds", "params":{"timelineName":"Timeline 1", "time":$(internal:custom_time)}}`
This will require you to enter a variable with the format eg. 2.5 (this is in seconds). Otherwise you can use:
`{"jsonrpc":"2.0", "id":44, "method":"Pixera.Compound.setCurrentTimeOfTimeline", "params":{"timelineName":"Timeline 1", "time":$(internal:custom_time)}}` This requires you to enter the variable in frames.

Hope this helps for now. Would be nice to have support for variables implemented in this module.

**Comment by BenniMTools** [comment]
variables are now supported for blendToTime and gotoTime
